/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .travis.yml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const firebase = {
  apiKey: "AIzaSyA30bWo9jOhSQ3zxQ8-W5g1I1DfzTNQ_pU",
  authDomain: "proyecto-diejavo.firebaseapp.com",
  databaseURL: "https://proyecto-diejavo.firebaseio.com",
  projectId: "proyecto-diejavo",
  storageBucket: "proyecto-diejavo.appspot.com"
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false, // enable/disable Firebase Database Logging
}

export const analyticsTrackingId = ''

export default {
  env,
  firebase,
  reduxFirebase,
  analyticsTrackingId
}